### ISSUE TITLE
Make the hook configurable

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/gulp-cordova-icon#11]
For all the information: https://github.com/SamVerschueren/gulp-cordova-icon/pull/10
##### TL;DR

The user should be able to use extra options like `stopOnError` and `warnOnError` to configure the flow of the hook. This should be done by using the [EJS](http://www.embeddedjs.com/) templating system.

@vincent-vieira will make a PR for this.

**Comment by vincent-vieira** [comment]
Just a quick question before working on it : as I was going through the source code, shall I extend this new error handling to critical functions of the hook like Cordova config.xml modification ?

Of course a comprehensive edit, like only adding warnings and still throwing critical blocking exceptions.

**Comment by SamVerschueren** [comment]
You mean if `loadConfig` or `updateConfig` fail, should it look at the options provided and stop or warn according to the configuration?

At the moment, if one of them fail, the error is thrown and the build stops. The reason is that if they fail, something is wrong with the config.xml file and I guess this means the build should not be proceeded at all.

What are your thoughts on this?

**Comment by vincent-vieira** [comment]
I had exactly the same thoughts, as I said these steps are crucial and if they don't go well, then the Cordova app won't package the right icons and may have a corrupted config.xml too. So basically, we can leave the actual handling as it is.

**Comment by SamVerschueren** [comment]
Released in v0.2.0
