### ISSUE TITLE
Resize don't work for iOS build.

### ISSUE THREAD

**Issue by readinglab2** [SamVerschueren/gulp-cordova-icon#17]
The generate icon file is not resized. The fix would be change follow line in icon.js:

gm(source).density(icon.dimension, icon.dimension).write(dest, next);

to:

gm(source).resize(icon.dimension, icon.dimension).write(dest, next);

**Comment by SamVerschueren** [comment]
Odd, I thought this was working with `png` files as well. The `density` call should be used with `svg` images. Will fix asap.

**Comment by SamVerschueren** [comment]
This is fixed in `0.3.0`. Thanks for reporting.
