### ISSUE TITLE
Split out the icon making functionality into a cmd npm package

### ISSUE THREAD

**Issue by ghost** [SamVerschueren/gulp-cordova-icon#19]
I'm no longer using cordova but I really liked the easy png/svg -> android/ios icons.

It would be great if that could be in an npm package that I can use.

`mobile-icon-generator`
`mig` path/to/my/pngorsvg

that would generate the needed image sizes with filenames, folder structure and supporting files (json for ios)

**Comment by SamVerschueren** [comment]
> It would be great if that could be in an npm package that I can use.

Should've splitted it in the first place :). Totally agree on this one.

If I'm not mistaken, Ionic might have this already. Maybe you can take a look at it? Please keep me updated on this. If it's not, might make a cli tool of it.

**Comment by ghost** [comment]
Looks like it does but it's cordova/iconic specific

**Comment by SamVerschueren** [comment]
So what you want is something like this

### Android

```
$ icogen android ~/icon.svg
generated 6 icons

$ ls
drawable          drawable-ldpi          drawable-mdpi
drawable-hdpi     drawable-xhdpi         drawable-xxhdpi
```

### iOS

```
$ icogen ios ~/icon.svg
generated 15 icons

$ ls
icons
```

...

**Comment by ghost** [comment]
yes!

**Comment by SamVerschueren** [comment]
Not much time left at the moment, so not sure when I will be able to split things up. But if you want to give it a go, I would be happy to review the code :).

**Comment by SamVerschueren** [comment]
@robertbaker Released a separate module and a CLI.
- [mobicon](https://github.com/SamVerschueren/mobicon)
- [mobicon-cli](https://github.com/SamVerschueren/mobicon-cli)
