### ISSUE TITLE
Wrong iOS folder?

### ISSUE THREAD

**Issue by petr001** [SamVerschueren/gulp-cordova-icon#23]
Hi,
I'm developing Cordova iPhone app and I'm using gulp-cordova-icon to setup custom app icon.
But images are generated wrongly in "{appName}/Resources/icons" instead "{appName}/Images.xcassets/AppIcon.appiconset" (which contains default cordova icons).

**Comment by SamVerschueren** [comment]
Which version of cordova are you using? Do you use `gulp-cordova-build-ios` to build the iOS application? The `{appName}/Resources/icons` is the location where iOS is looking for my icons to be honest. `{appName}/Images.xcassets/AppIcon.appiconset` doesn't even exist here.

But it's possible that that's the new location in newer/older cordova/ios versions.

**Comment by petr001** [comment]
I'm using cordova 5.0.0 and all your plugins:
"gulp-cordova-build-ios": "^1.1.0",
"gulp-cordova-create": "^1.2.0",
"gulp-cordova-icon": "^0.3.0",

I looked at `cordova-icon` plugin and there is also the path I was talking about:
https://github.com/AlexDisler/cordova-icon/blob/master/index.js

**Comment by SamVerschueren** [comment]
Thanks for the information @petr001. Have to look into it as it seems like a changed project structure somewhere, either cordova or xcode.

**Comment by petr001** [comment]
More from cordova-icon repo: https://github.com/AlexDisler/cordova-icon/issues/55

**Comment by ryd0rz** [comment]
Has anyone fixed this issue?

We were able to use gulp-cordova-icon recently, but not sure why it's broken?

**Comment by TheCertain** [comment]
I faced the very same issue (with Phonegap version 6.2.7) and fixed it in my fork https://github.com/TheCertain/gulp-cordova-icon (along with adding two missing icon formats for iOS). Just issued a pull request as well.
