### ISSUE TITLE
Add support for svg

### ISSUE THREAD

**Issue by ghost** [SamVerschueren/gulp-cordova-icon#7]
Both GraphicsMagick and ImageMagick support converting svg to png. It would be great if I can use a single SVG to generate the plaform icons instead of using a png.

**Comment by SamVerschueren** [comment]
Very good idea! Will definitely implement this one.

**Comment by SamVerschueren** [comment]
Thanks for the suggestion @robertbaker. This is added in `v0.1.0`.
