### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [SamVerschueren/gulp-cordova-icon#8]
I installed the plugin. It's copying my icon to .cordova/res/icon.png. I installed graphicsmagick on my system and installed npm i gm (which is missing from the docs). It's not creating the pngs into platforms.

I'm on windows

**Comment by SamVerschueren** [comment]
Hi Robert, thanks for reaching out to me. 

`gm` should not be installed by hand, it is installed by the plugin itself.

Can you provide me with the following information? 
1. What is the dimension of the icon?
2. What platform are you building for after using the plugin? The images are generated in a pre-build hook so it doesn't do much until a build is started.

**Comment by ghost** [comment]
My PNG is 512x512px. Building just Android. It seems like the icon prehook script is getting an error and doesn't show it to me. Because the icon plugin copies my icon from /src/assets/icon.png to /.cordova/res/icon.png.

There I assume the pre-hook takes res/icon.png and makes the needed images but fails to do so.

**Comment by SamVerschueren** [comment]
That indeed is how it works, or at least should work. Can you provide more information like the cordova version you are using?

You can also try to debug the hook by adding logs in the generate function https://github.com/SamVerschueren/gulp-cordova-icon/blob/master/hooks/before_prepare/icon.js#L126 or in other functions. It would be very helpfull.

**Comment by ghost** [comment]
@SamVerschueren Looks like I just needed to reboot my machine, guess it didn't pick up on the environment vars.
